### PR TITLE
Add section in README about release versioning

### PR DESCRIPTION
**Pull request by grantseltzer**
This describes @yanivagman's idea in #39.  I would immediately follow up this PR merge with the cutting of a new release based on the scheme described here.

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
> Major releases are cut when backwards compatibility is broken or major milestones are completed, such as reaching parity with libbpf's API.

Agreed.

> Minor releases are cut to incorporate new support for libbpf APIs.

Yes. If we follow a 1:1 feature with libbpf like we're doing, then this will work.

> Patch releases are cut to incorporate important individual or groupings of bug fixes.

Yes.

> libbpf support numbering indicates the minimum required libbpf version that must be linked in order to ensure libbpfgo compatibility. For example, v0.2.1-libbpf_0.4.0 means that version 0.2.1 of libbpfgo requires v0.4.0 or newer of libbpf.

Perfect.

--

Can we add a disclaimer like (and feel free to rephrase as English is better on your side):

Do note that some distributions might have local changes to their libbpf package and their version might include backports and/or fixes differently than upstream versions.

**Comment by grantseltzer** [comment]
> Can we add a disclaimer like (and feel free to rephrase as English is better on your side):
> 
> Do note that some distributions might have local changes to their libbpf package and their version might include backports and/or fixes differently than upstream versions. In those cases we recommend that libbpfgo is used statically compiled.

Great idea, and your english was perfect. Added.

> And then I can do a simple write on how to clone libbpfgo and write a oneliner and have it compiled with dynamic libbpfgo dependency and with static libbpfgo dependency.
> 
> What do you think ?

Sounds great!

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Comment by grantseltzer** [comment]
I pushed another commit when I realized I had some redundant information in my previous one. Also added a TOC. 

Also want to note that I confirmed having '-' or '_' doesn't break anything with versioning go modules.

**Pull request merged**
