### PR TITLE
checking if bpftool is installed

### PR DESCRIPTION
**Pull request by mtcherni95**
Solves: #105

### CODE REVIEW

**Review by rafaeldtinoco — COMMENTED** [review]
I want to change libbpfgo Makefile to something like we just did to tracee's Makefile.one checks: https://github.com/aquasecurity/tracee/blob/main/Makefile.one#L39

WDYT ? We can then check tools, libs and compilers versions like we're doing there. I need to update libbpfgo Makefile with similar changes (and to create a single Makefile) in libbpfgo.

@grantseltzer what do you think ?

With that change, we can make a build target to depend on "tools and versions checking" per make target.

**Comment by grantseltzer** [comment]
@rafaeldtinoco Your makefile wizardy would be great to have in libbpfgo, but for the sake of getting this change in before the next release (i'd like to cut it today) I think @mtcherni95's fix works well for now. Is that ok?

**Comment by rafaeldtinoco** [comment]
@grantseltzer its perfect and I agree. Its better to have this fix now then. I can work the Makefile for the next release (or even after Makefile.one is ready in tracee). Cheers!

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Pull request merged**
