### PR TITLE
add parser for mknod mode argument

### PR DESCRIPTION
**Pull request by roikol**

### CODE REVIEW

**Review by yanivagman — COMMENTED** [review]
How is this function any different from ParseInodeMode?

**Review by rafaeldtinoco — APPROVED** [review]
LGTM

**Review by yanivagman — CHANGES_REQUESTED** [review]
ParseInodeMode() should be good enough, I think.
Anyways, why not using uint32 for mode_t?

**Comment by roikol** [comment]
after talking with @yanivagman - ParseInodeMode() is good for my needs, so this new function ParseMknodMode() is not needed. closing the PR.

**Pull request closed without merging**
