### PR TITLE
Makefile: download libbpf submodule when not found

### PR DESCRIPTION
**Pull request by geyslan**
Making contribution easier.

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
This way an offline build would fail, wouldn't it ? Sometimes we may need to rsync the git tree to an offline node to test building, for example. Maybe to check if directory is empty and then try to update it ?

Not sure about the submodule managing by Makefile also, @grantseltzer what is your take on this ?

**Comment by geyslan** [comment]
>  Maybe to check if directory is empty and then try to update it ?

The rule already does something like that since `LIBBPF_SRC = $(abspath ./libbpf/src)`. So the rule only runs if `./libbpf/src` doesn't exist.

```Makefile
$(LIBBPF_SRC):
ifeq ($(wildcard $@), )
	echo "INFO: updating submodule 'libbpf'"
	$(GIT) submodule update --init --recursive
endif
```

**Comment by rafaeldtinoco** [comment]
> ifeq ($(wildcard $@), )

Sorry, missed that. Okay then, I'm ok with this.

**Review by grantseltzer — APPROVED** [review]
LGTM! Thanks so much @geyslan !

**Pull request merged**
