### PR TITLE
Update libbpf to v0.7.0

### PR DESCRIPTION
**Pull request by saschagrunert**
Update the git submodule to the latest release.

### CODE REVIEW

**Comment by grantseltzer** [comment]
Hi Sascha! Thanks for this. I will test libbpfgo against libbpf v0.7.0 this week. I have to plan merging this around a release of libbpfgo so I want to get my error handling PR merged before that. I will keep you updated here but it will take a week at the longest.

**Comment by grantseltzer** [comment]
I'm almost ready to approve/merge this, i'm just working on fixing the fac tthat our tcpconnect selftest uses the deprecated form of `perf_buffer__new()`. Shouldn't be more than a day to figure it out.

**Comment by grantseltzer** [comment]
Ok I will merge this right after https://github.com/aquasecurity/libbpfgo/pull/134

**Review by rafaeldtinoco — APPROVED** [review]
LGTM. @grantseltzer I'll let you merge both then, at your convenience.

**Pull request merged**
