### PR TITLE
chore(prog): Add autoattach api

### PR DESCRIPTION
**Pull request by chentao-kernel**

### CODE REVIEW

**Comment by chentao-kernel** [comment]
Add it！

**Comment by chentao-kernel** [comment]
> @chentao-kernel thank you for your contribution. Would you mind creating a selftest for this new API? You could follow this lead: https://github.com/aquasecurity/libbpfgo/tree/main/selftest/set-attach

hi,geyslan, no problem, i will do it latter, thank you for your reply!

**Comment by chentao-kernel** [comment]
> > @chentao-kernel thank you for your contribution. Would you mind creating a selftest for this new API? You could follow this lead: https://github.com/aquasecurity/libbpfgo/tree/main/selftest/set-attach
> 
> hi,geyslan, no problem, i will do it latter, thank you for your reply!

done, i also add 

> > @chentao-kernel thank you for your contribution. Would you mind creating a selftest for this new API? You could follow this lead: https://github.com/aquasecurity/libbpfgo/tree/main/selftest/set-attach
> 
> hi,geyslan, no problem, i will do it latter, thank you for your reply!

done!

**Comment by geyslan** [comment]
@chentao-kernel I've requested a pull from you in your own branch (changing the way it tests). Do you mind update it and push force? Thanks.

**Comment by chentao-kernel** [comment]
> @chentao-kernel I've requested a pull from you in your own branch (changing the way it tests). Do you mind update it and push force? Thanks.
hi, geyslan, thank you for your review, i megert it in my branch and update it, but bringing in some commits information，is it right?

**Comment by geyslan** [comment]
> [CLA assistant check](https://cla-assistant.io/aquasecurity/libbpfgo?pullRequest=406) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/libbpfgo?pullRequest=406) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/libbpfgo?pullRequest=406) it.

@chentao-kernel I think you miss that. After signing the CLA I can merge the PR.

**Comment by chentao-kernel** [comment]
> > [CLA assistant check](https://cla-assistant.io/aquasecurity/libbpfgo?pullRequest=406) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/libbpfgo?pullRequest=406) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/libbpfgo?pullRequest=406) it.
> 
> @chentao-kernel I think you miss that. After signing the CLA I can merge the PR.

Excuse me， now finished.

**Comment by chentao-kernel** [comment]
> > > [CLA assistant check](https://cla-assistant.io/aquasecurity/libbpfgo?pullRequest=406) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/libbpfgo?pullRequest=406) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/libbpfgo?pullRequest=406) it.
> > 
> > 
> > @chentao-kernel I think you miss that. After signing the CLA I can merge the PR.
> 
> Excuse me， now finished.

hi，geyslan, i saw the libbpf released some new feature, so libbpfgo developed base on the latest libbpf version or 
specify version, maybe i can participate in more development tasks.

**Comment by geyslan** [comment]
> hi，geyslan, i saw the libbpf released some new feature, so libbpfgo developed base on the latest libbpf version or
> specify version, maybe i can participate in more development tasks.

Feel free to pick some open issue or bring us new API functionalities.

Thank you for your contribution. ❤️

**Pull request merged**
