### PR TITLE
Update to libbpf v0.8.0

### PR DESCRIPTION
**Pull request by grantseltzer**
Signed-off-by: grantseltzer <grantseltzer@gmail.com>

### CODE REVIEW

**Review by rafaeldtinoco — DISMISSED** [review]
LGTM. Are you dealing with deprecated warnings later ?

**Comment by grantseltzer** [comment]
Yes, I've removed the deprecated function. We have BPFProg.SetProgramType() to use instead

**Review by rafaeldtinoco — APPROVED** [review]
LGTM. Go for it =D.

**Comment by rafaeldtinoco** [comment]
image
Pay attention to git log guidelines, we have a good example in tracee. Let me show you in next comment.

**Comment by rafaeldtinoco** [comment]
image

**Pull request merged**
