### PR TITLE
fix: re-introduce memory bumping

### PR DESCRIPTION
**Pull request by rafaeldtinoco**
make libbpfgo to bump rlimits instead of relying in libbpf to do so.

### CODE REVIEW

**Review by geyslan — APPROVED** [review]

**Comment by kakkoyun** [comment]
Hey @rafaeldtinoco, what was the reason for this revert? I couldn't find it. 

Would you also be open to making it configurable?  We'd love to disable it or find a way to specify the value of the lock. I'd be happy to contribute. I want to understand the reasoning and possible downsides.

**Comment by rafaeldtinoco** [comment]
> Hey @rafaeldtinoco, what was the reason for this revert? I couldn't find it.
> 
> Would you also be open to making it configurable? We'd love to disable it or find a way to specify the value of the lock. I'd be happy to contribute. I want to understand the reasoning and possible downsides.

@grantseltzer found out that libbpf wouldn't raise the limit in all cases and I believe he reported an issue upstrea, did you @grantseltzer ? Could you remind me what was the issue with libbpf missing the raise in some environments ?

**Comment by grantseltzer** [comment]
@kakkoyun @rafaeldtinoco  Yes I brought it up on the mailing list, you can find the thread [here](https://lore.kernel.org/bpf/CAEf4BzaMNU2UoutOLdX-HbkA0037EV6kwQg3-TJLHV_8tjdzDg@mail.gmail.com/) but essentially the summary is that it's a known issue on certain kernels to not be able to properly detect if the limit should manually be raised.

**Comment by rafaeldtinoco** [comment]
@kakkoyun feel free to suggest something to turn it into a tunable parameter!

**Comment by bobrik** [comment]
I made #337 to skip the bump on a tunable condition.

**Pull request merged**
