### PR TITLE
examples: Add tcpconnect as a libbpfgo example

### PR DESCRIPTION
**Pull request by rafaeldtinoco**
$ make -C examples/tcpconnect

will build:

- tcpconnect-static
- tcpconnect-dynamic
- tcpconnect-go-static
- tcpconnect-go-dynamic

as an example on how to use libbpfgo (or libbpf) to probe kernel
function "tcp_connection" and get data from it.

### CODE REVIEW

**Comment by grantseltzer** [comment]
Can you talk about your thinking around having selftests and examples as separate entities? What if this could be a selftest that has an additional helper program that makes a tcp connection?

If we do go with a separate examples directory can you update the top level README to point to the examples? We currently have a section that has a small usage example, and additionally points to selftests as examples.

**Comment by rafaeldtinoco** [comment]
> Can you talk about your thinking around having selftests and examples as separate entities? What if this could be a selftest that has an additional helper program that makes a tcp connection?

I don't have a hard opinion on it to be honest. Now that you mentioned, wouldn't be a bad idea after all (to make it a selftest).

> If we do go with a separate examples directory can you update the top level README to point to the examples? We currently have a section that has a small usage example, and additionally points to selftests as examples.

I wanted to instrument one to build a simple and yet functional golang and C program with instructions on how to do it and why things are being done the way they are.

Now I'm in doubt if we should have it as a selftest or provide a very good README explaining why things were done the way they were...

What is your opinion ?

**Comment by grantseltzer** [comment]
I'd say make it a selftest so we can point to a single place for people to look for examples of libbpfgo usage in the README, and maybe it'd even be a good blog post

**Comment by rafaeldtinoco** [comment]
I have turned the example into a selftest that does a small 127.0.0.1 connection in port 12345 as a magic escape to succeed:

```
make[1]: Entering directory '/home/rafaeldtinoco/work/sources/ebpf/libbpfgo/selftest/tcpconnect'
make -C /home/rafaeldtinoco/work/sources/ebpf/libbpfgo libbpfgo-static
make -C /home/rafaeldtinoco/work/sources/ebpf/libbpfgo vmlinuxh
make -C /home/rafaeldtinoco/work/sources/ebpf/libbpfgo libbpf-static
make[2]: Entering directory '/home/rafaeldtinoco/work/sources/ebpf/libbpfgo'
make[2]: Entering directory '/home/rafaeldtinoco/work/sources/ebpf/libbpfgo'
make[2]: Entering directory '/home/rafaeldtinoco/work/sources/ebpf/libbpfgo'
make[2]: Nothing to be done for 'libbpf-static'.
make[2]: Leaving directory '/home/rafaeldtinoco/work/sources/ebpf/libbpfgo'
CC=clang \
	CGO_CFLAGS="-I/home/rafaeldtinoco/work/sources/ebpf/libbpfgo/output" \
	CGO_LDFLAGS="-lelf -lz /home/rafaeldtinoco/work/sources/ebpf/libbpfgo/output/libbpf.a" \
	GOOS=linux GOARCH=amd64 \
	go build \
	-tags netgo -ldflags '-w -extldflags "-static"' \
	.
make[2]: Leaving directory '/home/rafaeldtinoco/work/sources/ebpf/libbpfgo'
clang -g -O2 -Wall -fpie -Wno-unused-variable -Wno-unused-function -target bpf -D__TARGET_ARCH_x86 -I../../output -c main.bpf.c -o main.bpf.o
make[2]: Leaving directory '/home/rafaeldtinoco/work/sources/ebpf/libbpfgo'
CC=clang \
	CGO_CFLAGS="-I/home/rafaeldtinoco/work/sources/ebpf/libbpfgo/output" \
	CGO_LDFLAGS="-lelf -lz /home/rafaeldtinoco/work/sources/ebpf/libbpfgo/output/libbpf.a" \
	GOARCH=amd64 \
	go build \
	-tags netgo -ldflags '-w -extldflags "-static"' \
	-o main-static ./main.go
/sbin/bpftool gen skeleton main.bpf.o > main.skel.h
clang "-I/home/rafaeldtinoco/work/sources/ebpf/libbpfgo/output" -lelf -lz -I../../output main.c -o main-c-static /home/rafaeldtinoco/work/sources/ebpf/libbpfgo/output/libbpf.a
sudo ./run.sh main-static
Listening for tcp_connect(), <Ctrl-C> or or SIG_TERM to end it.
nc (pid: 3837701) (loginuid: 1000) | (proto: 6) 127.0.0.1 (40108) => 127.0.0.1 (12345)
success
[*] SUCCESS: all good
sudo ./run.sh main-c-static
Listening for tcp_connect(), <Ctrl-C> or or SIG_TERM to end it.
nc (pid: 3837806) (loginuid: 1000) | (6) 127.0.0.1 (40110) => 127.0.0.1 (12345)
[*] SUCCESS: all good
```

It tests both: the golang and C based tcpconnect codes with the same logic. golang is the default one to be built and run.

**Comment by rafaeldtinoco** [comment]
MISSING: To add documentation regarding the selftest/tcpconnect example (so we can consider it a full example of C+LIBBPF versus GO+LIBBPFGO for end users).

**Comment by rafaeldtinoco** [comment]
I have created the following Readme.md file for this selftest:

https://github.com/rafaeldtinoco/libbpfgo/tree/main/selftest/tcpconnect

Original intent is to serve as an example for those willing to create a libbpfgo application.

With that, this is ready to be reviewed again @grantseltzer .

**Pull request closed without merging**
