### PR TITLE
workflows: trigger test-daily only by schedule

### PR DESCRIPTION
**Pull request by geyslan**
It removes PR triggering.

### CODE REVIEW

**Review by rafaeldtinoco — APPROVED** [review]
LGTM. BTW, question... are we keeping this test in libbpfgo OR in tracee only ? Because if we are testing this in tracee, and keeping a badge in that repository, then this repository would not need this test anymore, no ?

**Comment by rafaeldtinoco** [comment]
https://github.com/aquasecurity/tracee/pull/2064/commits/43c92bcd2613e4b4b12ed4ee386add68325ecf6c#r943831598

**Comment by geyslan** [comment]
Currently we have this workflow working in the current repo that tests `tracee` compilation using upstream libbfgo. We are creating the same test inside `tracee`https://github.com/aquasecurity/tracee/pull/2064. They are related workflows, but independent.

The PR tracee unique action dependency is on the usage of `aquasecurity/libbpfgo/.github/actions/build-dependencies`.

**Comment by geyslan** [comment]
Closing this due https://github.com/aquasecurity/tracee/pull/2064 and removals ([compile-tracee.sh](https://github.com/aquasecurity/libbpfgo/blob/main/testing/compile-tracee.sh) and [test-daily.yaml](https://github.com/aquasecurity/libbpfgo/blob/main/.github/workflows/test-daily.yaml)) PR to be raised.

**Pull request closed without merging**
