### PR TITLE
Upgrade libbpf to 1.1.0

### PR DESCRIPTION
**Pull request by mozillazg**
https://github.com/libbpf/libbpf/releases/tag/v1.1.0

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
@geyslan I think we should bump to the latest libbpf for our next tracee milestone (as we're currently using v1.0.1). WDYT ?

**Comment by geyslan** [comment]
I would suggest waiting a bit as we're dealing with an EPIC issue.

**Comment by geyslan** [comment]
Tracee tested (unit and integration) against this PR and everything is green. @yanivagman

**Review by geyslan — APPROVED** [review]
LGTM

**Comment by geyslan** [comment]
@mozillazg Thanks.

**Pull request merged**
